/*
 * Copyright (c) 2021, The UAPKI Project Authors.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are 
 * met:
 * 
 * 1. Redistributions of source code must retain the above copyright 
 * notice, this list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright 
 * notice, this list of conditions and the following disclaimer in the 
 * documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

public interface TestData {
    // Alice and Bob
    // https://en.wikipedia.org/wiki/Alice_and_Bob
    String B64_STRING_WIKI_ALICE_AND_BOB =
        "QWxpY2UgYW5kIEJvYgpodHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9BbGljZV9hbmRfQm9i";

    // The quick brown fox jumps over the lazy dog
    String B64_STRING_THE_QUICK_BROWN_FOX =
        "VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZw==";

    // Лагідна українізація
    String B64_STRING_GENTLE_UKRAINIZATION =
        "0JvQsNCz0ZbQtNC90LAg0YPQutGA0LDRl9C90ZbQt9Cw0YbRltGP";

    // This is base64 encoded document content
    String B64_STRING_TEST =
        "VGhpcyBpcyBiYXNlNjQgZW5jb2RlZCBkb2N1bWVudCBjb250ZW50Lg==";

    String B64_CERT_3DA_ROOT_DSTU4145 =
        "MIIFXjCCBNqgAwIBAgIUEMdyXCGZAmFSOWkAAAAAAAAAAAAwDQYLKoYkAgEBAQED" +
        "AQEwgbkxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjEaMBgGA1UECgwR" +
        "0KLQntCSICLQoS7Qhi7QoiIxETAPBgNVBAsMCNCd0JXQlNCfMTQwMgYDVQQDDCvQ" +
        "otC10YHRgtC+0LLQuNC5INCd0JXQlNCfINCi0J7QkiAi0KEu0IYu0KIiMRcwFQYD" +
        "VQRhDA5OVFJVQS0zODc3Mzg2OTEZMBcGA1UEBQwQVUEtMzg3NzM4NjktMjAyMjAe" +
        "Fw0yMjExMTgxNzA4MzlaFw0yNzExMTcxNzA4MzlaMIG5MQswCQYDVQQGEwJVQTER" +
        "MA8GA1UEBwwI0JrQuNGX0LIxGjAYBgNVBAoMEdCi0J7QkiAi0KEu0IYu0KIiMREw" +
        "DwYDVQQLDAjQndCV0JTQnzE0MDIGA1UEAwwr0KLQtdGB0YLQvtCy0LjQuSDQndCV" +
        "0JTQnyDQotCe0JIgItChLtCGLtCiIjEXMBUGA1UEYQwOTlRSVUEtMzg3NzM4Njkx" +
        "GTAXBgNVBAUMEFVBLTM4NzczODY5LTIwMjIwWzAeBgsqhiQCAQEBAQMBATAPBg0q" +
        "hiQCAQEBAQMBAQIJAzkABDbnvSjAx8p0XQvB3QkCncSzpfEAVkZB0T5evkTUfCF3" +
        "oE4DWET4tlTFZRfuaZmIjoRwlGuiREujggK3MIICszApBgNVHQ4EIgQgx3JcIZkC" +
        "YVI5adgH+GI0KPxzjQLe9oA6KQgpmega8PwwKwYDVR0jBCQwIoAgx3JcIZkCYVI5" +
        "adgH+GI0KPxzjQLe9oA6KQgpmega8PwwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB" +
        "/wQIMAYBAf8CAQAwPAYDVR0gBDUwMzAxBgkqhiQCAQEBAgIwJDAiBggrBgEFBQcC" +
        "ARYWaHR0cHM6Ly9jem8uZ292LnVhL2NwczByBggrBgEFBQcBAwRmMGQwCwYJKoYk" +
        "AgEBAQIBMAgGBgQAjkYBATAIBgYEAI5GAQQwKgYGBACORgEFMCAwHhYYaHR0cHM6" +
        "Ly9jem8uZ292LnVhL2Fib3V0EwJlbjAVBggrBgEFBQcLAjAJBgcEAIvsSQECMBoG" +
        "A1UdJQEB/wQQMA4GDCsGAQQBgZdGAQEIHzCBlwYDVR0fBIGPMIGMMESgQqBAhj5o" +
        "dHRwOi8vdmExLnNpdC5jb21wYW55L2Rvd25sb2FkL2NybHMvQ0EtM0RBLURTVFUt" +
        "MjAyMi1GdWxsLmNybDBEoEKgQIY+aHR0cDovL3ZhMi5zaXQuY29tcGFueS9kb3du" +
        "bG9hZC9jcmxzL0NBLTNEQS1EU1RVLTIwMjItRnVsbC5jcmwwgZkGA1UdLgSBkTCB" +
        "jjBFoEOgQYY/aHR0cDovL3ZhMS5zaXQuY29tcGFueS9kb3dubG9hZC9jcmxzL0NB" +
        "LTNEQS1EU1RVLTIwMjItRGVsdGEuY3JsMEWgQ6BBhj9odHRwOi8vdmEyLnNpdC5j" +
        "b21wYW55L2Rvd25sb2FkL2NybHMvQ0EtM0RBLURTVFUtMjAyMi1EZWx0YS5jcmww" +
        "MQYDVR0RBCowKIEOY2FAc2l0LmNvbXBhbnmCFmh0dHBzOi8vY2Euc2l0LmNvbXBh" +
        "bnkwDQYLKoYkAgEBAQEDAQEDbwAEbDC0C+e2Pr2kFxW/2Y78Fz2m6gs0AxjPWLa6" +
        "twmnBi4v4ShAb0r2cHfTaQd4W+Dl34F1yOSWAXRD1Kog4krqoobWiuA2rGqcqEeC" +
        "xHV5pwGQ2jU5mas16WOLay6jtiq1/YglhG7nddMMjtjyEQ==";

    String B64_CERT_3DA_DSTU4145 =
        "MIIF5jCCBWKgAwIBAgIUEMdyXCGZAmFSOWkAAAAAAAAAAIowDQYLKoYkAgEBAQED" +
        "AQEwgbkxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjEaMBgGA1UECgwR" +
        "0KLQntCSICLQoS7Qhi7QoiIxETAPBgNVBAsMCNCd0JXQlNCfMTQwMgYDVQQDDCvQ" +
        "otC10YHRgtC+0LLQuNC5INCd0JXQlNCfINCi0J7QkiAi0KEu0IYu0KIiMRcwFQYD" +
        "VQRhDA5OVFJVQS0zODc3Mzg2OTEZMBcGA1UEBQwQVUEtMzg3NzM4NjktMjAyMjAe" +
        "Fw0yMzAyMDYwMDAwMDBaFw0yNTAyMDYyMzU5NTlaMIGvMTIwMAYDVQQDDCnQotC1" +
        "0YHRgtC+0LLQuNC5INC60L7RgNC40YHRgtGD0LLQsNGHIDNEQTEbMBkGA1UEBQwS" +
        "VUEtMzMzMzMzMzMzMy0xMDI4MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX" +
        "0LIxITAfBgNVBCoMGNC60L7RgNC40YHRgtGD0LLQsNGHIDNEQTEZMBcGA1UEBAwQ" +
        "0KLQtdGB0YLQvtCy0LjQuTCB8jCByQYLKoYkAgEBAQEDAQEwgbkwdTAHAgIBAQIB" +
        "DAIBAAQhEL7j22rqnh+GV4xFwSWU/5QjlKfXOPkYfmUVAXKU9M4BAiEAgAAAAAAA" +
        "AAAAAAAAAAAAAGdZITrxgumH0+F3FJB9Rw0EIbYP0tjc6Kk0I8YQG8qRxHoAfmww" +
        "CybNVWybDn0g7ykqAARAqdbrRfE8cIKAxJZ7Ix9erfZY66TANykdONlr8CXKThf4" +
        "6XINxhW0OiiXXwvB3qNkOLVk6iwXn9ASPm24+sV5BAMkAAQhAfWjOH2783vhAZ1i" +
        "XEGQqAIw59eeI6Pb2EqzH7RUAx8Bo4ICsTCCAq0wKQYDVR0OBCIEIO1S0Z6UWeyZ" +
        "rThTpq1MceslrEyKuSQ4ouOInTrARBdPMCsGA1UdIwQkMCKAIMdyXCGZAmFSOWnY" +
        "B/hiNCj8c40C3vaAOikIKZnoGvD8MAwGA1UdEwQFMAMCAQAwDgYDVR0PAQH/BAQD" +
        "AgbAMF4GCCsGAQUFBwEDBFIwUDALBgkqhiQCAQEBAgEwKgYGBACORgEFMCAwHhYY" +
        "aHR0cHM6Ly9jem8uZ292LnVhL2Fib3V0EwJlbjAVBggrBgEFBQcLAjAJBgcEAIvs" +
        "SQEBMDwGA1UdIAQ1MDMwMQYJKoYkAgEBAQICMCQwIgYIKwYBBQUHAgEWFmh0dHBz" +
        "Oi8vY3pvLmdvdi51YS9jcHMwJwYDVR0JBCAwHjAcBgwqhiQCAQEBCwEEAQExDBMK" +
        "MzMzMzMzMzMzMzBQBgNVHR8ESTBHMEWgQ6BBhj9odHRwOi8vY2Euc2l0LmNvbXBh" +
        "bnkvZG93bmxvYWQvY3Jscy9yb290LTNkYS1kc3R1LTIwMjItZnVsbC5jcmwwUQYD" +
        "VR0uBEowSDBGoESgQoZAaHR0cDovL2NhLnNpdC5jb21wYW55L2Rvd25sb2FkL2Ny" +
        "bHMvcm9vdC0zZGEtZHN0dS0yMDIyLWRlbHRhLmNybDBBBggrBgEFBQcBCwQ1MDMw" +
        "MQYIKwYBBQUHMAOGJWh0dHA6Ly90c2ExLnNpdC5jb21wYW55L3NlcnZpY2VzL3Rz" +
        "cC8wgYUGCCsGAQUFBwEBBHkwdzAxBggrBgEFBQcwAYYlaHR0cDovL3ZhMS5zaXQu" +
        "Y29tcGFueS9zZXJ2aWNlcy9vY3NwLzBCBggrBgEFBQcwAoY2aHR0cDovL2NhLnNp" +
        "dC5jb21wYW55L2Rvd25sb2FkL2NlcnRpZmljYXRlcy9jYS0zZGEucDdiMA0GCyqG" +
        "JAIBAQEBAwEBA28ABGyqMtZQIKnrcI3vgYRsrF8fh7pc6SeltFeTJr3eeVgI4vGv" +
        "EvcS6I/scXtHUZzhWbTm8e5bCRF8FjkudJp8sCbPS8IXkFwDsI4Hj0LHLBIDK/ZS" +
        "wCLMLptsoh6lDEehz/y4+I6fxf8bJijk2wc=";

    String B64_CERT_DIIA_ROOT_DSTU4145 =
        "MIIGBzCCBYOgAwIBAgIUBeGeLNkuopkBAAAAAQAAAOEAAAAwDQYLKoYkAgEBAQED" +
        "AQEwggEXMVwwWgYDVQQKDFPQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0YbQuNGE" +
        "0YDQvtCy0L7RlyDRgtGA0LDQvdGB0YTQvtGA0LzQsNGG0ZbRlyDQo9C60YDQsNGX" +
        "0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotCh" +
        "INCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQ" +
        "stGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEt" +
        "NDMyMjA4NTEtMjAyMDELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyMB4X" +
        "DTIwMDYwMzA3MzkwMFoXDTI1MDYwMzA3MzkwMFowgeExFjAUBgNVBAoMDdCU0J8g" +
        "ItCU0IbQryIxczBxBgNVBAMMaiLQlNGW0Y8iLiDQmtCy0LDQu9GW0YTRltC60L7Q" +
        "stCw0L3QuNC5INC90LDQtNCw0LLQsNGHINC10LvQtdC60YLRgNC+0L3QvdC40YUg" +
        "0LTQvtCy0ZbRgNGH0LjRhSDQv9C+0YHQu9GD0LMxGTAXBgNVBAUTEFVBLTQzMzk1" +
        "MDMzLTEwMDAxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjEXMBUGA1UE" +
        "YQwOTlRSVUEtNDMzOTUwMzMwgfIwgckGCyqGJAIBAQEBAwEBMIG5MHUwBwICAQEC" +
        "AQwCAQAEIRC+49tq6p4fhleMRcEllP+UI5Sn1zj5GH5lFQFylPTOAQIhAIAAAAAA" +
        "AAAAAAAAAAAAAABnWSE68YLph9PhdxSQfUcNBCG2D9LY3OipNCPGEBvKkcR6AH5s" +
        "MAsmzVVsmw59IO8pKgAEQKnW60XxPHCCgMSWeyMfXq32WOukwDcpHTjZa/Alyk4X" +
        "+OlyDcYVtDool18Lwd6jZDi1ZOosF5/QEj5tuPrFeQQDJAAEISzoTm+PThWh3C1G" +
        "ZsSb9IhgQlet/KAHsJh3AQAkb/88AaOCAkEwggI9MCkGA1UdDgQiBCC+1QgxYNvF" +
        "m83fcHwQKT9Yu27SY8bqWJPTeBth9JO+VzAOBgNVHQ8BAf8EBAMCAQYwFwYDVR0l" +
        "BBAwDgYMKwYBBAGBl0YBAQgfMDwGA1UdIAQ1MDMwMQYJKoYkAgEBAQICMCQwIgYI" +
        "KwYBBQUHAgEWFmh0dHBzOi8vY3pvLmdvdi51YS9jcHMwLQYDVR0RBCYwJIIQY2Eu" +
        "aW5mb3JtanVzdC51YYEQY2FAaW5mb3JtanVzdC51YTASBgNVHRMBAf8ECDAGAQH/" +
        "AgEAMHIGCCsGAQUFBwEDBGYwZDAIBgYEAI5GAQEwCAYGBACORgEEMCoGBgQAjkYB" +
        "BTAgMB4WGGh0dHBzOi8vY3pvLmdvdi51YS9hYm91dBMCZW4wFQYIKwYBBQUHCwIw" +
        "CQYHBACL7EkBAjALBgkqhiQCAQEBAgEwKwYDVR0jBCQwIoAgBeGeLNkuopm8enaP" +
        "B12sTKukjqMlDl7AWY3IKN+AEaYwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2N6" +
        "by5nb3YudWEvZG93bmxvYWQvY3Jscy9DWk8tMjAyMC1GdWxsLmNybDBDBgNVHS4E" +
        "PDA6MDigNqA0hjJodHRwOi8vY3pvLmdvdi51YS9kb3dubG9hZC9jcmxzL0NaTy0y" +
        "MDIwLURlbHRhLmNybDA8BggrBgEFBQcBAQQwMC4wLAYIKwYBBQUHMAGGIGh0dHA6" +
        "Ly9jem8uZ292LnVhL3NlcnZpY2VzL29jc3AvMA0GCyqGJAIBAQEBAwEBA28ABGz+" +
        "gkhx/jLR23+dbqbNXUCn7dwxjQ3hiVkCpfonc2W/f3G5rw0WGMsKSIvc7gRhSrS8" +
        "0hTBqgxBil4mOqcZzEk5KtIcuJCW4CNZur5JeJx3qYEGreerYMMDt4CAKfAB3rQY" +
        "I2CAL5Ixo8MB3QQ=";

    String B64_CERT_DIIA_DSTU4145 =
        "MIIGKDCCBdCgAwIBAgIUPtUIMWDbxZsEAAAAqR4GAHOldgAwDQYLKoYkAgEBAQED" +
        "AQEwgeExFjAUBgNVBAoMDdCU0J8gItCU0IbQryIxczBxBgNVBAMMaiLQlNGW0Y8i" +
        "LiDQmtCy0LDQu9GW0YTRltC60L7QstCw0L3QuNC5INC90LDQtNCw0LLQsNGHINC1" +
        "0LvQtdC60YLRgNC+0L3QvdC40YUg0LTQvtCy0ZbRgNGH0LjRhSDQv9C+0YHQu9GD" +
        "0LMxGTAXBgNVBAUTEFVBLTQzMzk1MDMzLTEwMDAxCzAJBgNVBAYTAlVBMREwDwYD" +
        "VQQHDAjQmtC40ZfQsjEXMBUGA1UEYQwOTlRSVUEtNDMzOTUwMzMwHhcNMjIwNDA1" +
        "MTc1NzU5WhcNMjQwNDA1MTc1NzU5WjCBizErMCkGA1UECgwi0JTQnyDQlNCG0K8g" +
        "KNCi0LXRgdGC0YPQstCw0L3QvdGPKTErMCkGA1UEAwwi0JTQnyDQlNCG0K8gKNCi" +
        "0LXRgdGC0YPQstCw0L3QvdGPKTEPMA0GA1UEBRMGNDAxMDY1MQswCQYDVQQGEwJV" +
        "QTERMA8GA1UEBwwI0JrQuNGX0LIwgfIwgckGCyqGJAIBAQEBAwEBMIG5MHUwBwIC" +
        "AQECAQwCAQAEIRC+49tq6p4fhleMRcEllP+UI5Sn1zj5GH5lFQFylPTOAQIhAIAA" +
        "AAAAAAAAAAAAAAAAAABnWSE68YLph9PhdxSQfUcNBCG2D9LY3OipNCPGEBvKkcR6" +
        "AH5sMAsmzVVsmw59IO8pKgAEQKnW60XxPHCCgMSWeyMfXq32WOukwDcpHTjZa/Al" +
        "yk4X+OlyDcYVtDool18Lwd6jZDi1ZOosF5/QEj5tuPrFeQQDJAAEIaod9NfMFeD3" +
        "eoSIBsTKQDBi2HZfUsaWreQOCqQNDegpAaOCAxswggMXMCkGA1UdDgQiBCBbxsBu" +
        "4eAMFwDpKqeprXX4LTy3qbZuOpgCMgmyRRMxXDArBgNVHSMEJDAigCC+1QgxYNvF" +
        "m83fcHwQKT9Yu27SY8bqWJPTeBth9JO+VzAOBgNVHQ8BAf8EBAMCBsAwFAYDVR0l" +
        "BA0wCwYJKoYkAgEBAQMJMEkGA1UdIARCMEAwPgYJKoYkAgEBAQICMDEwLwYIKwYB" +
        "BQUHAgEWI2h0dHBzOi8vY2EuaW5mb3JtanVzdC51YS9yZWdsYW1lbnQvMAkGA1Ud" +
        "EwQCMAAwUgYIKwYBBQUHAQMERjBEMAgGBgQAjkYBATArBgYEAI5GAQUwITAfFhlo" +
        "dHRwczovL2NhLmluZm9ybWp1c3QudWEvEwJlbjALBgkqhiQCAQEBAgEwWAYDVR0R" +
        "BFEwT6AmBgwrBgEEAYGXRgEBBAGgFgwUKzM4ICgwIDY3KSAyMjAtNzYtNjeBEHZs" +
        "YWRrb0BnbWFpbC5jb22gEwYKKwYBBAGCNxQCA6AFDAMxMDgwTwYDVR0fBEgwRjBE" +
        "oEKgQIY+aHR0cDovL2NhLmluZm9ybWp1c3QudWEvZG93bmxvYWQvY3Jscy9DQS1C" +
        "RUQ1MDgzMS1GdWxsLVMxNy5jcmwwUAYDVR0uBEkwRzBFoEOgQYY/aHR0cDovL2Nh" +
        "LmluZm9ybWp1c3QudWEvZG93bmxvYWQvY3Jscy9DQS1CRUQ1MDgzMS1EZWx0YS1T" +
        "MTcuY3JsMIGFBggrBgEFBQcBAQR5MHcwMgYIKwYBBQUHMAGGJmh0dHA6Ly9jYS5p" +
        "bmZvcm1qdXN0LnVhL3NlcnZpY2VzL29jc3AvMEEGCCsGAQUFBzAChjVodHRwOi8v" +
        "Y2EuaW5mb3JtanVzdC51YS91cGxvYWRzL2NlcnRpZmljYXRlcy9kaWlhLnA3YjBB" +
        "BggrBgEFBQcBCwQ1MDMwMQYIKwYBBQUHMAOGJWh0dHA6Ly9jYS5pbmZvcm1qdXN0" +
        "LnVhL3NlcnZpY2VzL3RzcC8wJQYDVR0JBB4wHDAaBgwqhiQCAQEBCwEEAgExChMI" +
        "NDMzOTUwMzMwDQYLKoYkAgEBAQEDAQEDQwAEQNVIZYi2/lo6aTCreacYKJ6OKgqH" +
        "stT28TLs4kMbUrVqvVQKMNxqZZTVFVUPQwh5LBnJU2virF9ynY6vuyxc+UY=";

    String B64_PFX_3DA_DSTU4145 =
        "MIIE4wIBAzCCBIAGCSqGSIb3DQEHAaCCBHEEggRtMIIEaTCCBGUGCSqGSIb3DQEH" +
        "AaCCBFYEggRSMIIETjCCAfIGCyqGSIb3DQEMCgECoIIBrjCCAaowgbAGCSqGSIb3" +
        "DQEFDTCBojBDBgkqhkiG9w0BBQwwNgQgMJ575Iz7TneJILzOoyJ4dr43Ea4rqb75" +
        "eSCSdRAT9ZsCAicQMA4GCiqGJAIBAQEBAQIFADBbBgsqhiQCAQEBAQEBAzBMBAju" +
        "EMs7VffM1gRAqdbrRfE8cIKAxJZ7Ix9erfZY66TANykdONlr8CXKThf46XINxhW0" +
        "OiiXXwvB3qNkOLVk6iwXn9ASPm24+sV5BASB9NM73PzQNan9/Z8LWFSlHiH+H0YS" +
        "fa+K95nJVR1/+IEZAeAhBpeLEJ7dXI8lubLoi+RLsVUBcAQ8/ezVC98M2pOV0d4Q" +
        "jxpabEKQ60wX7L2sTCX0gI+6PAZmaeQzdQIQjAwmbFw4Tcmn1FQGbb6PhI7Mk59H" +
        "GTATJVJHxkV0jkgj6Y2YlLh8PEDESeFueDV0ZoY6qneC66pp+gpwfsAP3Qkv/Veh" +
        "wGJ4SzTw8R0BBk254h7UYbnEF9a1BkaAoR7cOoas5UDow7tT7G/r4dO8A85kVRfj" +
        "JxVwvz+OspUTfNTYM9vq8Z80VJ0a7XWc64bBN5GlW/wxMTAvBgkqhkiG9w0BCRUx" +
        "IgQg7VLRnpRZ7JmtOFOmrUxx6yWsTIq5JDii44idOsBEF08wggJUBgsqhkiG9w0B" +
        "DAoBAqCCAhAwggIMMIGwBgkqhkiG9w0BBQ0wgaIwQwYJKoZIhvcNAQUMMDYEIJED" +
        "WCsAiSbnGVzoW91spF95wPWE6E7Hhbq8FgHY+b/pAgInEDAOBgoqhiQCAQEBAQEC" +
        "BQAwWwYLKoYkAgEBAQEBAQMwTAQIpWA7eLfA1xwEQKnW60XxPHCCgMSWeyMfXq32" +
        "WOukwDcpHTjZa/Alyk4X+OlyDcYVtDool18Lwd6jZDi1ZOosF5/QEj5tuPrFeQQE" +
        "ggFVK3WENGlwJ6lW0BwGw5gibO+AA+RjJSbpUHvthGb1chw9ZDxFsSDVD9mET75T" +
        "FgKgpIMDRuWSht1KGkQj4zTIlEyG6PKIgWIy6KcXducDC1fEPbYsGbgFv+D2jXpl" +
        "/Fs5LOTbJ4boyoY5GCgpKsczUHSt2X0RR7MUlIsMJrMLdPsq+2uz/L9PYulmLd3J" +
        "Mu81YgtJC8nHAm2fD1DDd8h9T/1vVrunFaxJ4a/hAcLPJuo3YqG+ZeXXlzcX87J3" +
        "iwoMWnh+ryuF5FLKtfRUOQsWUq1JEiYiVPfF7J3HZPlV8lc0FWBGyDYx5SRvyBlQ" +
        "J1g3QFYqJo6xYrYYVN8rVcwNiMiS4WUqsz3OPECTUyK7Pfwi4faFmeMj4t4ZdpRm" +
        "xGjDY2qfvNW8jDIsvSjX+yrAvMYslaK+Y1Q4dRODyYOzpPpflmY4prqwDRXAQXRB" +
        "KS0zx3tqkXkxMTAvBgkqhkiG9w0BCRUxIgQgVUA7DHRTQvH5OWBu87bzZ93ZQk4F" +
        "2csWqJ3FfkdebrwwWjAyMA4GCiqGJAIBAQEBAgEFAAQg9SQSXJHMfBVTXQmrY62S" +
        "KZ/bnGO9K+tSdzz8MaA+Gs4EIMn1Er6cChjwO5Ym/7/0TJUr0VRo8Y6Cr5k0etmy" +
        "lmjNAgInEA==";

    String B64_BUNDLE_P7B =
        "MIIQcQYJKoZIhvcNAQcCoIIQYjCCEF4CAQExADALBgkqhkiG9w0BBwGgggxdMIIC" +
        "gzCCAiqgAwIBAgITItlzhSagVcanqjjwzwOYZCEJzDAKBggqhkjOPQQDAjCBlzEL" +
        "MAkGA1UEBhMCVUExFTATBgNVBAgMDNCu0LrRgNC10LnQvTEVMBMGA1UEBwwM0KXQ" +
        "sNGA0LrRltCyMRYwFAYDVQQKDA3QntGE0ZbRgSwgTHRkMRcwFQYDVQQLDA5SJkQg" +
        "RGVwYXJ0bWVudDEpMCcGA1UEAwwg0J/RgNC40LrQu9Cw0LQgRUNEU0EocHJpbWUy" +
        "NTZ2MSkwHhcNMjAwMjExMTIwODQ2WhcNMjEwMjEwMTIwODQ2WjCBlzELMAkGA1UE" +
        "BhMCVUExFTATBgNVBAgMDNCu0LrRgNC10LnQvTEVMBMGA1UEBwwM0KXQsNGA0LrR" +
        "ltCyMRYwFAYDVQQKDA3QntGE0ZbRgSwgTHRkMRcwFQYDVQQLDA5SJkQgRGVwYXJ0" +
        "bWVudDEpMCcGA1UEAwwg0J/RgNC40LrQu9Cw0LQgRUNEU0EocHJpbWUyNTZ2MSkw" +
        "WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASotjrEH00aiJZ8QzCxZG4zl8uenJoL" +
        "qMcFKl+KZPZPipGGEf0baRAzxqAqjtDVDQnkTCGgKaTgklwOa6eqlDleo1MwUTAd" +
        "BgNVHQ4EFgQURflz4d2dbY06MDmpyX7SCUAy3xQwHwYDVR0jBBgwFoAURflz4d2d" +
        "bY06MDmpyX7SCUAy3xQwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBE" +
        "AiBaqFEPDeSHUFGigPUaDs1h+kfTCGxjSk3sMuDYmva17QIgWRLCfx4kfGV4EjXV" +
        "3bVF7NpXmMokvsufxFAQWV6g+BgwggLAMIICRqADAgECAhQtFOq8zGxg51bOQ6uu" +
        "hSQsQWb2xzAKBggqhkjOPQQDAjCBljELMAkGA1UEBhMCVUExFTATBgNVBAgMDNCu" +
        "0LrRgNC10LnQvTEVMBMGA1UEBwwM0KXQsNGA0LrRltCyMRYwFAYDVQQKDA3QntGE" +
        "0ZbRgSwgTHRkMRcwFQYDVQQLDA5SJkQgRGVwYXJ0bWVudDEoMCYGA1UEAwwf0J/R" +
        "gNC40LrQu9Cw0LQgRUNEU0Eoc2VjcDM4NHIxKTAeFw0yMDAyMTExMjA4NDZaFw0y" +
        "MTAyMTAxMjA4NDZaMIGWMQswCQYDVQQGEwJVQTEVMBMGA1UECAwM0K7QutGA0LXQ" +
        "udC9MRUwEwYDVQQHDAzQpdCw0YDQutGW0LIxFjAUBgNVBAoMDdCe0YTRltGBLCBM" +
        "dGQxFzAVBgNVBAsMDlImRCBEZXBhcnRtZW50MSgwJgYDVQQDDB/Qn9GA0LjQutC7" +
        "0LDQtCBFQ0RTQShzZWNwMzg0cjEpMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEjPge" +
        "6htElZ+0Ydl4oolNrPv8hTaGu+CbFJgQLNfkQx1s3pK/eJhgggWOEdfnPsJk58MS" +
        "85QJOPilY4Obak1cO/Tw/xKMAl/4SX09g1tkYWgOdSQL/Pa3+6IHrSNU6k/co1Mw" +
        "UTAdBgNVHQ4EFgQUz+9680kEHTd1AxzuqbfTFeLD6gMwHwYDVR0jBBgwFoAUz+96" +
        "80kEHTd1AxzuqbfTFeLD6gMwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNo" +
        "ADBlAjEA3xTNjSFW8pZ/wKmwYa2kvifiF4x6neL88DCh/H8icXAnnldE9pvKY3NS" +
        "U5ji5jsJAjBU1cAYsNmQDpQ56op532RPgW6mkwzb+IabgGVmMYFbFMVAHjtGK9cv" +
        "UlreMUrfGd0wggMJMIICbKADAgECAhQYiRUL3YAQ0kzp6kiU1/yndrvdpTAKBggq" +
        "hkjOPQQDAjCBljELMAkGA1UEBhMCVUExFTATBgNVBAgMDNCu0LrRgNC10LnQvTEV" +
        "MBMGA1UEBwwM0KXQsNGA0LrRltCyMRYwFAYDVQQKDA3QntGE0ZbRgSwgTHRkMRcw" +
        "FQYDVQQLDA5SJkQgRGVwYXJ0bWVudDEoMCYGA1UEAwwf0J/RgNC40LrQu9Cw0LQg" +
        "RUNEU0Eoc2VjcDUyMXIxKTAeFw0yMDAyMTExMjA4NDZaFw0yMTAyMTAxMjA4NDZa" +
        "MIGWMQswCQYDVQQGEwJVQTEVMBMGA1UECAwM0K7QutGA0LXQudC9MRUwEwYDVQQH" +
        "DAzQpdCw0YDQutGW0LIxFjAUBgNVBAoMDdCe0YTRltGBLCBMdGQxFzAVBgNVBAsM" +
        "DlImRCBEZXBhcnRtZW50MSgwJgYDVQQDDB/Qn9GA0LjQutC70LDQtCBFQ0RTQShz" +
        "ZWNwNTIxcjEpMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBlMfdSy8UXwJkryyh" +
        "Yv+SIVJSbVuoDaf3uUsN2lC1I3P4Zfiez598CJmKgR3r9TrkayLY8Fb4tT/v6JSR" +
        "uZCdSYsBLPpsTJNNtUdt1v73+vhu3Kcdkx/CBvBXfPq6raTfL8agd2WH4TON1mau" +
        "2PenOJDLwY8VEdt2SoWa/lZTB+Bd3LCjUzBRMB0GA1UdDgQWBBTVGquPuUwcbD65" +
        "LAbkqGu2Y10r6TAfBgNVHSMEGDAWgBTVGquPuUwcbD65LAbkqGu2Y10r6TAPBgNV" +
        "HRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA4GKADCBhgJBAz0H6BYMt3K5I/g8l678" +
        "1pJNg1WZ1GqU5js8nxGfwPFNKfjftpWlK02cX77RVR0jlB7DnuRVkZY1IRsEw6P1" +
        "zHwCQUtFSyskjMkUYzUzklnWXlnO15hBZ7T+9rSTVCdtLPXokUchk0cnVtbiYUFU" +
        "yz4VUD522rcgQ8J0JN4o2ptF7hdFMIIEATCCAumgAwIBAgIUKelDQp6S/9nkGnQS" +
        "H6V0WpCp28cwDQYJKoZIhvcNAQELBQAwgY8xCzAJBgNVBAYTAlVBMRUwEwYDVQQI" +
        "DAzQrtC60YDQtdC50L0xFTATBgNVBAcMDNCl0LDRgNC60ZbQsjEWMBQGA1UECgwN" +
        "0J7RhNGW0YEsIEx0ZDEXMBUGA1UECwwOUiZEIERlcGFydG1lbnQxITAfBgNVBAMM" +
        "GNCf0YDQuNC60LvQsNC0IFJTQSgyMDQ4KTAeFw0yMDAyMTExMjA4NDdaFw0yMTAy" +
        "MTAxMjA4NDdaMIGPMQswCQYDVQQGEwJVQTEVMBMGA1UECAwM0K7QutGA0LXQudC9" +
        "MRUwEwYDVQQHDAzQpdCw0YDQutGW0LIxFjAUBgNVBAoMDdCe0YTRltGBLCBMdGQx" +
        "FzAVBgNVBAsMDlImRCBEZXBhcnRtZW50MSEwHwYDVQQDDBjQn9GA0LjQutC70LDQ" +
        "tCBSU0EoMjA0OCkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCp+iU7" +
        "C86NI2m0mU8ninS1T/buiSqe2jYLpO6TXa/fJ0qmVAondpSERoodNw8itZQnlVOi" +
        "KycTYL3YURzdK661bZ/iD4vx+TkT7fULWkWt/DOrotrYjvXV6mWeJt9ScfwTIp0A" +
        "RRfHca9aLi8stiFQvxQ1Cr1dFSpAqkA0ug60oSSUszbMvLBvLss7n/OxRITzk7aD" +
        "dgMOSm6399n5G7zIVSVL/ZibWPPSO63HhUkzQyLo1Z6c9knFp8bFNlps7AP0LSKY" +
        "fvNyMepSdVIawTE3x96TwF12lxI1MHT+2aHN5OdfWDf8i2WeRhvdQWsEQ91mDrqk" +
        "qKzQ7vNtabZh9dsnAgMBAAGjUzBRMB0GA1UdDgQWBBThNn7wEBfwUFjXUBn7yli/" +
        "aIbGgTAfBgNVHSMEGDAWgBThNn7wEBfwUFjXUBn7yli/aIbGgTAPBgNVHRMBAf8E" +
        "BTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBVH/j0vwHTkgGjCOnp0XerHZXxxV6q" +
        "YIVyeCntJ8GIlaattntJOaA2xzZUJ04xEtn+k2Ohvva3KEeszwL5r5n+4Ig/bVXY" +
        "6Xy9speL8Q7/j/aFJqrgZ8lyvobd61o7kEWuYL7Bws2SIxpT1B8mfJ2V3AQCSyOG" +
        "xEaq2CHVB6UugWT1Ug3zQA3ihCCgFnqpsqGrxaUBtEFqCd00cOFgGThIS4JFC2vu" +
        "TXISGoXW5EO8yCvJ7YxAH7VkMtS0iH+BQUx5KMMQfh8TcJt5h9Y+gdybuprL11Rd" +
        "3vbtidQpa1pbf8xUFqbJnbAxkOePelK6Q09Q6Q9CEUU/T2quZQcPpah3oYID5TCC" +
        "A+EwggHJAgEBMA0GCSqGSIb3DQEBCwUAMIG5MSowKAYDVQQKDCFCcmFuY2ggTUlD" +
        "QyBvZiBKU0MgVWtyemFsaXpueXRzaWExDDAKBgNVBAsMA0NTSzEtMCsGA1UEAwwk" +
        "VWtyemFsaXpueXRzaWEgQ2VydGlmaWNhdGUgYXV0aG9yaXR5MRkwFwYDVQQFDBBV" +
        "QS00MDA4MTI1OC0yMDE4MQswCQYDVQQGEwJVQTENMAsGA1UEBwwES3lpdjEXMBUG" +
        "A1UEYQwOTlRSVUEtNDAwODEyNTgXDTE5MDMxNTEwMTUyNloXDTE5MDMyMjEwMTUy" +
        "NlowTzBNAhRY89S0YVoaogQAAADzAAMAtuwGABcNMTgxMTIzMTA0MzM0WjAmMAoG" +
        "A1UdFQQDCgEAMBgGA1UdGAQRGA8yMDE4MTEyMzEwNDMzNFqggYkwgYYwDAYDVR0U" +
        "BAUCAwK59jBJBgNVHS4EQjBAMD6gPKA6hjhodHRwOi8vY3NrLnV6Lmdvdi51YS9k" +
        "b3dubG9hZC9jcmxzL0NBLUQ4RjNENEI0LURlbHRhLmNybDArBgNVHSMEJDAigCDY" +
        "89S0YVoaovPpdTz6xUg3cu8XOAAAAAAAAAAAAAAAADANBgkqhkiG9w0BAQsFAAOC" +
        "AgEANfUbQG8NFeYMAETkFt1GYjDCg5XikNrJ2+II+8TaR7FdrEplhgo2TttZu2VZ" +
        "GLqayS1xSjY1/dgLjz4cq0CdvJsVezkwE8GsS6EUN6uyc47nJVZFPWtXtxYu67C3" +
        "1H4tMmEOW6KOY2Sn3YXBxbsL3k79Mm/zt70+t3WurtMytf4ypJRxt5PTInOuDaFB" +
        "i3I6u6BsvBnEUZnid7pomuhd0T7pbmPxFeY+aF/TOZlriqsziFdSdxphW4MBpDBD" +
        "bGDBEefWruXeZ4PwpcC63yz6KHSRO8JYOMyDfi97/T5n98nrt57f2nRM5HQmbH3Q" +
        "CYjN/qnD6otAAGyGXE96mLt4xfbt8OmyI1V64CkmLRk47xkwzWwu7SqawJKM/XSF" +
        "OeU0U6/xjIhdOpbGxXQluos0EMmerck4iT20pdCM2j8hvJ1n5CEqMFwB6JKceOB9" +
        "ya0lZVBj5Md9wAtsjyS4oiNCmJZhEJNeWZEUlyt0tqiryJ6zcXv6D9jbJpeqaBVC" +
        "hSzi5QH/m/cIV0Xyn/C3rJjm2VUyaHYayxd7Aqf28AJuDpA3nuB3Y0ucTVj1Pj+D" +
        "OROLEGptexL/kcuHEIuoyESiOORXCC3tgLJD68B3lobw9MiXKiRtDjBxFzclxMcc" +
        "mvtF12yGg1g4fEqzQidmCnuy03uZIzPkvLOQDKCjuLYz6TIxAA==";

    String B64_CRL_FULL_25_REVOKEDCERTS =
        "MIIJajCCCRICAQEwDQYLKoYkAgEBAQEDAQEwgeUxCzAJBgNVBAYTAlVBMRkwFwYD" +
        "VQQFExBVQS0zODc3Mzg2OS0wMDAxMT8wPQYDVQQDDDbQptC10L3RgtGAINGB0LXR" +
        "gNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgIjNEQSIxVjBUBgNVBAoM" +
        "TdCi0J7QkiAi0IbQvdGC0LXQs9GA0L7QstCw0L3RliDRltC90YTQvtGA0LzQsNGG" +
        "0ZbQudC90ZYg0YLQtdGF0L3QvtC70L7Qs9GW0ZciMQ8wDQYDVQQLDAbQptCh0Jox" +
        "ETAPBgNVBAcMCNCa0LjRl9CyFw0yMTA3MjcwNjExMThaFw0yMTA4MDMwNTQxNTJa" +
        "MIIHtzBNAhQVd5G5UIhX7QQAAAAGAAAAEQAAABcNMTkwMTExMTYzMjM5WjAmMAoG" +
        "A1UdFQQDCgEEMBgGA1UdGAQRGA8yMDE5MDExMTE2MzIzOVowTQIUFXeRuVCIV+0E" +
        "AAAACQAAABsAAAAXDTE5MDMxNTA5MTYzOVowJjAKBgNVHRUEAwoBBDAYBgNVHRgE" +
        "ERgPMjAxOTAzMTUwOTE2MzlaME0CFBV3kblQiFftBAAAAAkAAAAcAAAAFw0xOTAz" +
        "MTUwOTE2NTlaMCYwCgYDVR0VBAMKAQQwGAYDVR0YBBEYDzIwMTkwMzE1MDkxNjU5" +
        "WjBNAhQVd5G5UIhX7QQAAAAIAAAAFAAAABcNMTkwNDE3MTUxNjIyWjAmMAoGA1Ud" +
        "FQQDCgEEMBgGA1UdGAQRGA8yMDE5MDQxNzE1MTYyMlowTQIUFXeRuVCIV+0EAAAA" +
        "BwAAABMAAAAXDTE5MDQxNzE1MTg0M1owJjAKBgNVHRUEAwoBBDAYBgNVHRgEERgP" +
        "MjAxOTA0MTcxNTE4NDNaME0CFBV3kblQiFftBAAAAAoAAAAhAAAAFw0xOTA2MjEx" +
        "ODQ2MzFaMCYwCgYDVR0VBAMKAQQwGAYDVR0YBBEYDzIwMTkwNjIxMTg0NjMxWjBN" +
        "AhQVd5G5UIhX7QQAAAAUAAAANQAAABcNMTkxMTA3MTQyMDA2WjAmMAoGA1UdFQQD" +
        "CgEGMBgGA1UdGAQRGA8yMDE5MTEwNzE0MjAwNlowTQIUFXeRuVCIV+0EAAAAGgAA" +
        "ADkAAAAXDTIwMDExNDEyMjUxNlowJjAKBgNVHRUEAwoBBjAYBgNVHRgEERgPMjAy" +
        "MDAxMTQxMjI1MTZaME0CFBV3kblQiFftBAAAABoAAAA5AAAAFw0yMDAxMTQxNzM1" +
        "NDRaMCYwCgYDVR0VBAMKAQgwGAYDVR0YBBEYDzIwMjAwMTE0MTczNTQ0WjBNAhQV" +
        "d5G5UIhX7QQAAAAbAAAAPgAAABcNMjAwMTIyMTU1MjQ3WjAmMAoGA1UdFQQDCgEE" +
        "MBgGA1UdGAQRGA8yMDIwMDEyMjE1NTI0N1owTQIUFXeRuVCIV+0EAAAAHgAAAEQA" +
        "AAAXDTIwMDMyMzE0MjIxN1owJjAKBgNVHRUEAwoBBDAYBgNVHRgEERgPMjAyMDAz" +
        "MjMxNDIyMTdaME0CFBV3kblQiFftBAAAAB4AAABFAAAAFw0yMDAzMjMxNDI0Mjda" +
        "MCYwCgYDVR0VBAMKAQUwGAYDVR0YBBEYDzIwMjAwMzIzMTQyNDI3WjBNAhQVd5G5" +
        "UIhX7QQAAAApAAAAUAAAABcNMjAwNTAzMTkzNjMzWjAmMAoGA1UdFQQDCgEEMBgG" +
        "A1UdGAQRGA8yMDIwMDUwMzE5MzYzM1owTQIUFXeRuVCIV+0EAAAAEgAAAC0AAAAX" +
        "DTIwMDYwMzEzMDEyNlowJjAKBgNVHRUEAwoBBDAYBgNVHRgEERgPMjAyMDA2MDMx" +
        "MzAxMjZaME0CFBV3kblQiFftBAAAABkAAAA4AAAAFw0yMDA4MjAyMzM0MjVaMCYw" +
        "CgYDVR0VBAMKAQYwGAYDVR0YBBEYDzIwMjAwODIwMjMzNDI1WjBNAhQVd5G5UIhX" +
        "7QQAAAAZAAAAOAAAABcNMjAwODIxMTAyODU5WjAmMAoGA1UdFQQDCgEIMBgGA1Ud" +
        "GAQRGA8yMDIwMDgyMTEwMjg1OVowTQIUFXeRuVCIV+0EAAAANQAAAFwAAAAXDTIw" +
        "MDgyNjIwMjgzN1owJjAKBgNVHRUEAwoBBjAYBgNVHRgEERgPMjAyMDA4MjYyMDI4" +
        "MzdaME0CFBV3kblQiFftBAAAADUAAABcAAAAFw0yMDA4MjYyMDMyMThaMCYwCgYD" +
        "VR0VBAMKAQgwGAYDVR0YBBEYDzIwMjAwODI2MjAzMjE4WjBNAhQVd5G5UIhX7QQA" +
        "AAA1AAAAXAAAABcNMjAwODMxMTU1OTU5WjAmMAoGA1UdFQQDCgEGMBgGA1UdGAQR" +
        "GA8yMDIwMDgzMTE1NTk1OVowTQIUFXeRuVCIV+0EAAAANQAAAFwAAAAXDTIwMDgz" +
        "MTE2MDEwOVowJjAKBgNVHRUEAwoBCDAYBgNVHRgEERgPMjAyMDA4MzExNjAxMDla" +
        "ME0CFBV3kblQiFftBAAAADoAAABxAAAAFw0yMDEyMDcxOTIzNTlaMCYwCgYDVR0V" +
        "BAMKAQQwGAYDVR0YBBEYDzIwMjAxMjA3MTkyMzU5WjBNAhQVd5G5UIhX7QQAAAA7" +
        "AAAAcgAAABcNMjAxMjA3MTkyNDIwWjAmMAoGA1UdFQQDCgEEMBgGA1UdGAQRGA8y" +
        "MDIwMTIwNzE5MjQyMFowTQIUFXeRuVCIV+0EAAAAOwAAAHQAAAAXDTIwMTIwNzE5" +
        "MzAwMFowJjAKBgNVHRUEAwoBBDAYBgNVHRgEERgPMjAyMDEyMDcxOTMwMDBaME0C" +
        "FBV3kblQiFftBAAAADwAAAB2AAAAFw0yMDEyMjMwNjUyMzhaMCYwCgYDVR0VBAMK" +
        "AQQwGAYDVR0YBBEYDzIwMjAxMjIzMDY1MjM4WjBNAhQVd5G5UIhX7QQAAAASAAAA" +
        "WAAAABcNMjEwNjA4MTMzMTA1WjAmMAoGA1UdFQQDCgEGMBgGA1UdGAQRGA8yMDIx" +
        "MDYwODEzMzEwNVqgPTA7MCsGA1UdIwQkMCKAINAGmqCo331wetcLL1QMsfsZHyId" +
        "DDjnH+E/m7aeoozHMAwGA1UdFAQFAgMBQtMwDQYLKoYkAgEBAQEDAQEDQwAEQAQE" +
        "+RN9A8eny8jOPmMdGP02A3+CHd8dAY1pUaIXUj5hXK501fvp70NH1t0GLCLty3x4" +
        "vGxUrzxA15Wd5gBHHCg=";

    String B64_CRL_DELTA_0_REVOKEDCERTS =
        "MIIBwDCCAWgCAQEwDQYLKoYkAgEBAQEDAQEwgeUxCzAJBgNVBAYTAlVBMRkwFwYD" +
        "VQQFExBVQS0zODc3Mzg2OS0wMDAxMT8wPQYDVQQDDDbQptC10L3RgtGAINGB0LXR" +
        "gNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgIjNEQSIxVjBUBgNVBAoM" +
        "TdCi0J7QkiAi0IbQvdGC0LXQs9GA0L7QstCw0L3RliDRltC90YTQvtGA0LzQsNGG" +
        "0ZbQudC90ZYg0YLQtdGF0L3QvtC70L7Qs9GW0ZciMQ8wDQYDVQQLDAbQptCh0Jox" +
        "ETAPBgNVBAcMCNCa0LjRl9CyFw0yMTA3MjgxODExMjBaFw0yMTA3MjgyMDExMTha" +
        "oE4wTDAPBgNVHRsBAf8EBQIDAULTMCsGA1UdIwQkMCKAINAGmqCo331wetcLL1QM" +
        "sfsZHyIdDDjnH+E/m7aeoozHMAwGA1UdFAQFAgMBQ60wDQYLKoYkAgEBAQEDAQED" +
        "QwAEQP2ntaLPv4OEsDKTkhh+nR9dWbxakFcmF/V8FAgLu+o5CF+zJT5kdRXgC84r" +
        "yK4if6DAVtZXWaeEa/kB2QCpY0Q=";

    String B64_P7S_3DA_DSTU4145 =
        "MIIMlgYJKoZIhvcNAQcCoIIMhzCCDIMCAQExDjAMBgoqhiQCAQEBAQIBMAsGCSqG" +
        "SIb3DQEHAaCCBeowggXmMIIFYqADAgECAhQQx3JcIZkCYVI5aQAAAAAAAAAAijAN" +
        "BgsqhiQCAQEBAQMBATCBuTELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9Cy" +
        "MRowGAYDVQQKDBHQotCe0JIgItChLtCGLtCiIjERMA8GA1UECwwI0J3QldCU0J8x" +
        "NDAyBgNVBAMMK9Ci0LXRgdGC0L7QstC40Lkg0J3QldCU0J8g0KLQntCSICLQoS7Q" +
        "hi7QoiIxFzAVBgNVBGEMDk5UUlVBLTM4NzczODY5MRkwFwYDVQQFDBBVQS0zODc3" +
        "Mzg2OS0yMDIyMB4XDTIzMDIwNjAwMDAwMFoXDTI1MDIwNjIzNTk1OVowga8xMjAw" +
        "BgNVBAMMKdCi0LXRgdGC0L7QstC40Lkg0LrQvtGA0LjRgdGC0YPQstCw0YcgM0RB" +
        "MRswGQYDVQQFDBJVQS0zMzMzMzMzMzMzLTEwMjgxCzAJBgNVBAYTAlVBMREwDwYD" +
        "VQQHDAjQmtC40ZfQsjEhMB8GA1UEKgwY0LrQvtGA0LjRgdGC0YPQstCw0YcgM0RB" +
        "MRkwFwYDVQQEDBDQotC10YHRgtC+0LLQuNC5MIHyMIHJBgsqhiQCAQEBAQMBATCB" +
        "uTB1MAcCAgEBAgEMAgEABCEQvuPbauqeH4ZXjEXBJZT/lCOUp9c4+Rh+ZRUBcpT0" +
        "zgECIQCAAAAAAAAAAAAAAAAAAAAAZ1khOvGC6YfT4XcUkH1HDQQhtg/S2NzoqTQj" +
        "xhAbypHEegB+bDALJs1VbJsOfSDvKSoABECp1utF8TxwgoDElnsjH16t9ljrpMA3" +
        "KR042WvwJcpOF/jpcg3GFbQ6KJdfC8Heo2Q4tWTqLBef0BI+bbj6xXkEAyQABCEB" +
        "9aM4fbvze+EBnWJcQZCoAjDn154jo9vYSrMftFQDHwGjggKxMIICrTApBgNVHQ4E" +
        "IgQg7VLRnpRZ7JmtOFOmrUxx6yWsTIq5JDii44idOsBEF08wKwYDVR0jBCQwIoAg" +
        "x3JcIZkCYVI5adgH+GI0KPxzjQLe9oA6KQgpmega8PwwDAYDVR0TBAUwAwIBADAO" +
        "BgNVHQ8BAf8EBAMCBsAwXgYIKwYBBQUHAQMEUjBQMAsGCSqGJAIBAQECATAqBgYE" +
        "AI5GAQUwIDAeFhhodHRwczovL2N6by5nb3YudWEvYWJvdXQTAmVuMBUGCCsGAQUF" +
        "BwsCMAkGBwQAi+xJAQEwPAYDVR0gBDUwMzAxBgkqhiQCAQEBAgIwJDAiBggrBgEF" +
        "BQcCARYWaHR0cHM6Ly9jem8uZ292LnVhL2NwczAnBgNVHQkEIDAeMBwGDCqGJAIB" +
        "AQELAQQBATEMEwozMzMzMzMzMzMzMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9j" +
        "YS5zaXQuY29tcGFueS9kb3dubG9hZC9jcmxzL3Jvb3QtM2RhLWRzdHUtMjAyMi1m" +
        "dWxsLmNybDBRBgNVHS4ESjBIMEagRKBChkBodHRwOi8vY2Euc2l0LmNvbXBhbnkv" +
        "ZG93bmxvYWQvY3Jscy9yb290LTNkYS1kc3R1LTIwMjItZGVsdGEuY3JsMEEGCCsG" +
        "AQUFBwELBDUwMzAxBggrBgEFBQcwA4YlaHR0cDovL3RzYTEuc2l0LmNvbXBhbnkv" +
        "c2VydmljZXMvdHNwLzCBhQYIKwYBBQUHAQEEeTB3MDEGCCsGAQUFBzABhiVodHRw" +
        "Oi8vdmExLnNpdC5jb21wYW55L3NlcnZpY2VzL29jc3AvMEIGCCsGAQUFBzAChjZo" +
        "dHRwOi8vY2Euc2l0LmNvbXBhbnkvZG93bmxvYWQvY2VydGlmaWNhdGVzL2NhLTNk" +
        "YS5wN2IwDQYLKoYkAgEBAQEDAQEDbwAEbKoy1lAgqetwje+BhGysXx+HulzpJ6W0" +
        "V5Mmvd55WAji8a8S9xLoj+xxe0dRnOFZtObx7lsJEXwWOS50mnywJs9LwheQXAOw" +
        "jgePQscsEgMr9lLAIswum2yiHqUMR6HP/Lj4jp/F/xsmKOTbBzGCBnEwggZtAgEB" +
        "MIHSMIG5MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIxGjAYBgNVBAoM" +
        "EdCi0J7QkiAi0KEu0IYu0KIiMREwDwYDVQQLDAjQndCV0JTQnzE0MDIGA1UEAwwr" +
        "0KLQtdGB0YLQvtCy0LjQuSDQndCV0JTQnyDQotCe0JIgItChLtCGLtCiIjEXMBUG" +
        "A1UEYQwOTlRSVUEtMzg3NzM4NjkxGTAXBgNVBAUMEFVBLTM4NzczODY5LTIwMjIC" +
        "FBDHclwhmQJhUjlpAAAAAAAAAACKMAwGCiqGJAIBAQEBAgGgggUyMAkGAioDMQMC" +
        "AQEwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjMw" +
        "MjEwMDU1MTM0WjAvBgkqhkiG9w0BCQQxIgQgKKm4W4tb3HzyiVA0VvTb8jiLy6Jj" +
        "oX93YdWd8Qdz8j8wggEoBgsqhkiG9w0BCRACLzGCARcwggETMIIBDzCCAQswDAYK" +
        "KoYkAgEBAQECAQQgA9Ct56fcUr6B6JNTdcWLT2klZwJqBhaBJ+e0KVhb4YEwgdgw" +
        "gb+kgbwwgbkxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjEaMBgGA1UE" +
        "CgwR0KLQntCSICLQoS7Qhi7QoiIxETAPBgNVBAsMCNCd0JXQlNCfMTQwMgYDVQQD" +
        "DCvQotC10YHRgtC+0LLQuNC5INCd0JXQlNCfINCi0J7QkiAi0KEu0IYu0KIiMRcw" +
        "FQYDVQRhDA5OVFJVQS0zODc3Mzg2OTEZMBcGA1UEBQwQVUEtMzg3NzM4NjktMjAy" +
        "MgIUEMdyXCGZAmFSOWkAAAAAAAAAAIowggOOBgsqhkiG9w0BCRACFDGCA30wggN5" +
        "BgkqhkiG9w0BBwKgggNqMIIDZgIBATEOMAwGCiqGJAIBAQEBAgEweQYLKoZIhvcN" +
        "AQkQAQSgagRoMGYCAQEGCiqGJAIBAQECAwEwMDAMBgoqhiQCAQEBAQIBBCAoqbhb" +
        "i1vcfPKJUDRW9NvyOIvLomOhf3dh1Z3xB3PyPwIIAWOMfEgAAHAYDzIwMjMwMjEw" +
        "MTIyOTI0WgIIJkLm+iSLx1YxggLUMIIC0AIBATCB0jCBuTELMAkGA1UEBhMCVUEx" +
        "ETAPBgNVBAcMCNCa0LjRl9CyMRowGAYDVQQKDBHQotCe0JIgItChLtCGLtCiIjER" +
        "MA8GA1UECwwI0J3QldCU0J8xNDAyBgNVBAMMK9Ci0LXRgdGC0L7QstC40Lkg0J3Q" +
        "ldCU0J8g0KLQntCSICLQoS7Qhi7QoiIxFzAVBgNVBGEMDk5UUlVBLTM4NzczODY5" +
        "MRkwFwYDVQQFDBBVQS0zODc3Mzg2OS0yMDIyAhQQx3JcIZkCYVI5aQAAAAAAAAAA" +
        "eDAMBgoqhiQCAQEBAQIBoIIBlTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwG" +
        "CSqGSIb3DQEJBTEPFw0yMzAyMTAxMjI5MjRaMC8GCSqGSIb3DQEJBDEiBCDh1uXJ" +
        "LXdds2u6v/NAqlrRExrN/CvG5/HWmuJbkTDZ4zCCASgGCyqGSIb3DQEJEAIvMYIB" +
        "FzCCARMwggEPMIIBCzAMBgoqhiQCAQEBAQIBBCCrrLRDLekX2hK4/76RTa8DvomW" +
        "h+uG0szo0N/3R0/X5DCB2DCBv6SBvDCBuTELMAkGA1UEBhMCVUExETAPBgNVBAcM" +
        "CNCa0LjRl9CyMRowGAYDVQQKDBHQotCe0JIgItChLtCGLtCiIjERMA8GA1UECwwI" +
        "0J3QldCU0J8xNDAyBgNVBAMMK9Ci0LXRgdGC0L7QstC40Lkg0J3QldCU0J8g0KLQ" +
        "ntCSICLQoS7Qhi7QoiIxFzAVBgNVBGEMDk5UUlVBLTM4NzczODY5MRkwFwYDVQQF" +
        "DBBVQS0zODc3Mzg2OS0yMDIyAhQQx3JcIZkCYVI5aQAAAAAAAAAAeDANBgsqhiQC" +
        "AQEBAQMBAQRAccBbkHEYyggqPdeHUA0PMNvzs3VTrol/4Ts6zalOzF24nZANOnK2" +
        "UETfUMR1s3h7cBpOTdz31np+QMagVw3+WzANBgsqhiQCAQEBAQMBAQRA23BZIBn2" +
        "lnLYXXlC0xAXNNqTF0ZDSUtl9y2VwEGq6iqlTOOqhesNuDAVd2SyCzSrHE8DOGo0" +
        "Ddgigikbr9VMZg==";
}
